# typed: false
# frozen_string_literal: true

# Generated by packages/cli/scripts/gen-homebrew-formula.mjs from the cli-v0.5.0 release — do not edit by
# hand; the release CD regenerates + pushes this on every tag.
class Wbhk < Formula
  desc "Capture, inspect, and replay webhooks from your terminal (webhook.co CLI)"
  homepage "https://webhook.co"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.5.0/wbhk-darwin-arm64"
      sha256 "afce1c34aebb15611cc8cdfb1d9adfab4a533f0465565321a84236543856c57e"
    end
    on_intel do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.5.0/wbhk-darwin-x64"
      sha256 "07da29ef38addb37570e0320c37f18f801932716cbd569d6f65a130196536f22"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.5.0/wbhk-linux-arm64"
      sha256 "b276dba50ed38ae871b501c1f1092a80c35ba19182bab31ad3a8b94938b10946"
    end
    on_intel do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.5.0/wbhk-linux-x64"
      sha256 "a1d93c05636fe25c520b87bb0988778c15700b31f75bfac213acce7da5d47d8e"
    end
  end

  def install
    # The release asset is a single bare binary (named per platform); install it as `wbhk`.
    bin.install Dir["wbhk-*"].first => "wbhk"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wbhk --version")
  end
end
