# typed: false
# frozen_string_literal: true

# Generated by packages/cli/scripts/gen-homebrew-formula.mjs from the cli-v0.3.0 release — do not edit by
# hand; the release CD regenerates + pushes this on every tag.
class Wbhk < Formula
  desc "Capture, inspect, and replay webhooks from your terminal (webhook.co CLI)"
  homepage "https://webhook.co"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.3.0/wbhk-darwin-arm64"
      sha256 "ffd02f90b119f6d56f64da639bda4c9ddc57c3ab702ba98c127a1f50ecaf1252"
    end
    on_intel do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.3.0/wbhk-darwin-x64"
      sha256 "614789169cb2dd7ba9dc6afa50c276d0ce7670c3506ff20d12a9339842c9023d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.3.0/wbhk-linux-arm64"
      sha256 "ff07acf3b106aeda24be8ed1798f3c0e7c963ad909ce88b56adb6afdd1796424"
    end
    on_intel do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.3.0/wbhk-linux-x64"
      sha256 "1ff884c61fc55687c659dcd03bfd82b49f44f387340868f8f62d8106031b4d10"
    end
  end

  def install
    # The release asset is a single bare binary (named per platform); install it as `wbhk`.
    bin.install Dir["wbhk-*"].first => "wbhk"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wbhk --version")
  end
end
