# typed: false
# frozen_string_literal: true

# Generated by packages/cli/scripts/gen-homebrew-formula.mjs from the cli-v0.1.2 release — do not edit by
# hand; the release CD regenerates + pushes this on every tag.
class Wbhk < Formula
  desc "Capture, inspect, and replay webhooks from your terminal (webhook.co CLI)"
  homepage "https://webhook.co"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.1.2/wbhk-darwin-arm64"
      sha256 "4bbb607f5daab9131a5c369706d0238b1c1bf0c5d1f3bf9eb18001d26cc17c70"
    end
    on_intel do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.1.2/wbhk-darwin-x64"
      sha256 "3bd9cc0aeee0c8ee57fd4785856811c78200e9471eda789c1135061f5f6ce48e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.1.2/wbhk-linux-arm64"
      sha256 "cca03e0f1e66b2e44ccdf85a106e9a9d82837fed5c03bf8588fb60d980bd96f0"
    end
    on_intel do
      url "https://github.com/webhook-co/webhook/releases/download/cli-v0.1.2/wbhk-linux-x64"
      sha256 "7726fd847421eb603e7b6a8272668fb711d85ff15dbd2b120ac5fd7be951af55"
    end
  end

  def install
    # The release asset is a single bare binary (named per platform); install it as `wbhk`.
    bin.install Dir["wbhk-*"].first => "wbhk"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wbhk --version")
  end
end
